import { CategoryConfig } from "@/lib/onboarding/types";

export const coachingConfig: CategoryConfig = {
  id: "cat_coaching",
  slug: "coaching",
  name: "Coaching & Tuitions",
  icon: "BookOpen",
  description: "Competitive Exams, JEE, NEET, UPSC, SSC, Banking, School & Coding Classes",
  sections: [
    {
      id: "coaching_overview",
      title: "Institute & Exam Focus",
      description: "Primary competitive exam streams and teaching methodology",
      fields: [
        {
          id: "coach_streams",
          name: "targetExams",
          label: "Exams & Streams Coached",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "JEE Main & Advanced (Engineering)", value: "jee" },
            { label: "NEET UG (Medical Entrance)", value: "neet" },
            { label: "UPSC / State PSC Civil Services", value: "upsc" },
            { label: "SSC (CGL, CHSL, CPO, GD)", value: "ssc" },
            { label: "Banking (IBPS, SBI PO & Clerk)", value: "banking" },
            { label: "Defence (NDA, CDS, AFCAT)", value: "defence" },
            { label: "CAT, MAT & MBA Entrance", value: "cat_mba" },
            { label: "CLAT & Law Entrance", value: "clat_law" },
            { label: "CA / CS / CMA Commerce Foundation", value: "ca_cs" },
            { label: "CUET (College Entrance)", value: "cuet" },
            { label: "School Tuition (Class 9th to 12th PCM/PCB/Commerce)", value: "school_tuition" },
            { label: "Coding, Web Development & Data Science", value: "coding_it" },
            { label: "IELTS, TOEFL & Spoken English", value: "spoken_english" },
          ],
        },
        {
          id: "coach_modes",
          name: "deliveryModes",
          label: "Batch Delivery Modes",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "Offline Classroom Coaching", value: "offline" },
            { label: "Live Online Interactive Classes", value: "live_online" },
            { label: "Hybrid (Classroom + Online Backup)", value: "hybrid" },
            { label: "Recorded Video Courses & Notes", value: "recorded" },
          ],
        },
      ],
    },
    {
      id: "courses_batches",
      title: "Batches & Course Offerings",
      description: "Add courses, durations, fees, and batch details",
      fields: [
        {
          id: "coach_batches_list",
          name: "batches",
          label: "Courses & Batches",
          type: "repeatable_group",
          required: true,
          minItems: 1,
          fields: [
            {
              id: "b_name",
              name: "batchName",
              label: "Course / Batch Title",
              type: "text",
              required: true,
              placeholder: "e.g. Target NEET 2027 Complete 2-Year Batch",
            },
            {
              id: "b_exam",
              name: "targetCategory",
              label: "Target Exam / Class",
              type: "text",
              required: true,
              placeholder: "e.g. NEET UG / 11th + 12th",
            },
            {
              id: "b_duration",
              name: "durationMonths",
              label: "Duration (Months)",
              type: "number",
              required: true,
              placeholder: "e.g. 12",
              validation: { min: 1, max: 48 },
            },
            {
              id: "b_fee",
              name: "totalFee",
              label: "Total Course Fee (₹)",
              type: "currency",
              required: true,
              placeholder: "e.g. 65000",
              validation: { min: 500 },
            },
            {
              id: "b_timing",
              name: "timingSlot",
              label: "Batch Timing Slot",
              type: "select",
              options: [
                { label: "Morning Batch (7 AM - 11 AM)", value: "morning" },
                { label: "Afternoon Batch (12 PM - 4 PM)", value: "afternoon" },
                { label: "Evening Batch (4 PM - 8 PM)", value: "evening" },
                { label: "Weekend Only Batch (Sat & Sun)", value: "weekend" },
              ],
            },
            {
              id: "b_installments",
              name: "installmentAllowed",
              label: "Fee Installments / EMI Available",
              type: "switch",
              defaultValue: true,
            },
          ],
        },
      ],
    },
    {
      id: "coaching_features",
      title: "Teaching Features & Facilities",
      description: "Study material, test series, demo classes, and facilities",
      fields: [
        {
          id: "coach_demo",
          name: "freeDemoClass",
          label: "Free Trial / Demo Class Available (2-3 Days)",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "coach_features_list",
          name: "instituteFeatures",
          label: "Institute Inclusions & Facilities",
          type: "checkbox_group",
          options: [
            { label: "Printed Comprehensive Study Material", value: "study_material" },
            { label: "All-India / Weekly Mock Test Series", value: "test_series" },
            { label: "Daily Doubt Solving Counters & Mentors", value: "doubt_sessions" },
            { label: "Air Conditioned Soundproof Classrooms", value: "ac_classrooms" },
            { label: "Self-Study Library & Reading Room", value: "library" },
            { label: "Mobile App for Online Tests & Recorded Lectures", value: "mobile_app" },
            { label: "Biometric Attendance & Parent SMS Alerts", value: "attendance_alerts" },
          ],
        },
        {
          id: "coach_faculty",
          name: "facultyHighlights",
          label: "Faculty Highlights & Past Achievements",
          type: "textarea",
          placeholder: "e.g. Taught by ex-IITians and top medical doctors with 15+ years experience. Produced AIR 45 in NEET 2025.",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "coaching_registration",
      label: "Institute Registration Certificate / MSME / Shop Act",
      description: "Proof of business registration for educational establishment",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
