import { CategoryConfig } from "@/lib/onboarding/types";

export const collegeConfig: CategoryConfig = {
  id: "cat_college",
  slug: "college",
  name: "College & Higher Education",
  icon: "GraduationCap",
  description: "Universities, Engineering, Medical, Management & Degree Colleges",
  sections: [
    {
      id: "college_overview",
      title: "Institution Overview",
      description: "Affiliation, university details, and accreditation status",
      fields: [
        {
          id: "coll_type",
          name: "institutionType",
          label: "College / University Type",
          type: "select",
          required: true,
          options: [
            { label: "Engineering & Technology Institute", value: "engineering" },
            { label: "Medical / Dental College", value: "medical" },
            { label: "Management / Business School", value: "management" },
            { label: "Law College / University", value: "law" },
            { label: "Pharmacy College", value: "pharmacy" },
            { label: "Arts, Science & Commerce College", value: "arts_science_commerce" },
            { label: "Computer Applications & IT Institute", value: "computer_it" },
            { label: "Polytechnic & Diploma College", value: "polytechnic" },
            { label: "Nursing & Paramedical College", value: "nursing" },
            { label: "Education & B.Ed / D.El.Ed College", value: "education" },
            { label: "Agriculture & Veterinary College", value: "agriculture" },
            { label: "Architecture & Design College", value: "architecture" },
          ],
        },
        {
          id: "coll_affiliation",
          name: "affiliatingUniversity",
          label: "Affiliated University / Board",
          type: "text",
          required: true,
          placeholder: "e.g. Dr. A.P.J. Abdul Kalam Technical University (AKTU)",
        },
        {
          id: "coll_naac_grade",
          name: "naacGrade",
          label: "NAAC Accreditation Grade",
          type: "select",
          options: [
            { label: "NAAC A++", value: "a_plus_plus" },
            { label: "NAAC A+", value: "a_plus" },
            { label: "NAAC A", value: "a" },
            { label: "NAAC B++", value: "b_plus_plus" },
            { label: "NAAC B+", value: "b_plus" },
            { label: "NAAC B", value: "b" },
            { label: "Not Accredited / Under Process", value: "none" },
          ],
        },
        {
          id: "coll_approved_by",
          name: "regulatoryApproval",
          label: "Approved By",
          type: "checkbox_group",
          options: [
            { label: "UGC Approved", value: "ugc" },
            { label: "AICTE Approved", value: "aicte" },
            { label: "NMC / MCI Approved", value: "nmc" },
            { label: "BCI (Bar Council of India)", value: "bci" },
            { label: "PCI (Pharmacy Council)", value: "pci" },
            { label: "NCTE (Teacher Education)", value: "ncte" },
            { label: "COA (Council of Architecture)", value: "coa" },
          ],
        },
      ],
    },
    {
      id: "courses_offered",
      title: "Courses & Programs Offered",
      description: "Add degree programs, intake seats, and fee structure",
      fields: [
        {
          id: "coll_courses_list",
          name: "courses",
          label: "Academic Courses",
          type: "repeatable_group",
          required: true,
          minItems: 1,
          fields: [
            {
              id: "c_name",
              name: "courseName",
              label: "Course / Degree Name",
              type: "text",
              required: true,
              placeholder: "e.g. B.Tech Computer Science & Engineering",
            },
            {
              id: "c_level",
              name: "degreeLevel",
              label: "Degree Level",
              type: "select",
              required: true,
              options: [
                { label: "Undergraduate (UG / Bachelor)", value: "ug" },
                { label: "Postgraduate (PG / Master)", value: "pg" },
                { label: "Diploma / Certificate", value: "diploma" },
                { label: "Doctorate (Ph.D)", value: "phd" },
              ],
            },
            {
              id: "c_duration",
              name: "durationYears",
              label: "Duration (Years)",
              type: "number",
              required: true,
              placeholder: "e.g. 4",
              validation: { min: 1, max: 6 },
            },
            {
              id: "c_seats",
              name: "totalSeats",
              label: "Total Intake Seats",
              type: "number",
              required: true,
              placeholder: "e.g. 120",
              validation: { min: 1 },
            },
            {
              id: "c_annual_fee",
              name: "annualFee",
              label: "Annual Tuition Fee (₹)",
              type: "currency",
              required: true,
              placeholder: "e.g. 95000",
              validation: { min: 1000 },
            },
            {
              id: "c_eligibility",
              name: "eligibilityCriteria",
              label: "Eligibility Criteria",
              type: "text",
              placeholder: "e.g. 10+2 with 60% in PCM + Valid JEE Score",
            },
          ],
        },
      ],
    },
    {
      id: "campus_facilities",
      title: "Campus Facilities & Placements",
      description: "Hostel, laboratory, sports, and career placement highlights",
      fields: [
        {
          id: "coll_facilities",
          name: "campusFacilities",
          label: "Campus Infrastructure",
          type: "checkbox_group",
          options: [
            { label: "Boys Hostel on Campus", value: "boys_hostel" },
            { label: "Girls Hostel on Campus", value: "girls_hostel" },
            { label: "Central Digital Library", value: "digital_library" },
            { label: "High-Tech Computer & Science Labs", value: "advanced_labs" },
            { label: "Sports Complex & Grounds", value: "sports_complex" },
            { label: "AC Auditorium / Seminar Halls", value: "auditorium" },
            { label: "Campus-Wide Wi-Fi", value: "wifi" },
            { label: "Bus / Transportation Facility", value: "transport" },
            { label: "Cafeteria & Food Court", value: "cafeteria" },
            { label: "Medical / Health Center", value: "medical_center" },
          ],
        },
        {
          id: "coll_highest_pkg",
          name: "highestPackageLPA",
          label: "Highest Placement Package (LPA in ₹)",
          type: "number",
          placeholder: "e.g. 24.5",
        },
        {
          id: "coll_avg_pkg",
          name: "averagePackageLPA",
          label: "Average Placement Package (LPA in ₹)",
          type: "number",
          placeholder: "e.g. 6.2",
        },
        {
          id: "coll_top_recruiters",
          name: "topRecruiters",
          label: "Top Recruiting Companies",
          type: "textarea",
          placeholder: "e.g. TCS, Infosys, Wipro, Amazon, HCL, L&T",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "university_affiliation_letter",
      label: "University Affiliation / Recognition Letter",
      description: "Official government or affiliating university approval document",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "aicte_ugc_approval",
      label: "AICTE / UGC / Regulatory Approval Letter",
      description: "Approval letter from relevant statutory council",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
