import { CategoryConfig } from "@/lib/onboarding/types";

export const dentalConfig: CategoryConfig = {
  id: "cat_dental",
  slug: "dental",
  name: "Dental Care & Clinics",
  icon: "Smile",
  description: "Dentists, Dental Clinics, Orthodontic, Implant & Smile Centers",
  sections: [
    {
      id: "dentist_profile",
      title: "Practitioner & Clinic Profile",
      description: "Dentist credentials, council registration, and clinic setup",
      fields: [
        {
          id: "dent_doc_name",
          name: "leadDentistName",
          label: "Principal / Lead Dentist Name",
          type: "text",
          required: true,
          placeholder: "e.g. Dr. Amit Sharma",
        },
        {
          id: "dent_qualification",
          name: "qualifications",
          label: "Qualifications & Degrees",
          type: "text",
          required: true,
          placeholder: "e.g. BDS, MDS (Orthodontics & Dentofacial Orthopedics)",
        },
        {
          id: "dent_reg_number",
          name: "councilRegistrationNumber",
          label: "Dental Council Registration Number",
          type: "text",
          required: true,
          placeholder: "e.g. UP-DCI-14523",
        },
        {
          id: "dent_experience",
          name: "yearsOfExperience",
          label: "Years of Clinical Experience",
          type: "number",
          required: true,
          placeholder: "e.g. 12",
          validation: { min: 0, max: 60 },
        },
        {
          id: "dent_consultation_fee",
          name: "consultationFee",
          label: "Initial Consultation Fee (₹)",
          type: "currency",
          required: true,
          placeholder: "e.g. 300",
          validation: { min: 0 },
        },
      ],
    },
    {
      id: "dental_treatments",
      title: "Treatments & Specializations",
      description: "Procedures and specialized dental treatments offered",
      fields: [
        {
          id: "dent_procedures",
          name: "treatmentsOffered",
          label: "Procedures & Treatments Offered",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "Single-Sitting Root Canal (RCT)", value: "rct" },
            { label: "Dental Implants (Single & Full Mouth)", value: "implants" },
            { label: "Invisible Clear Aligners & Braces", value: "aligners_braces" },
            { label: "Laser Teeth Whitening & Bleaching", value: "teeth_whitening" },
            { label: "Zirconia & Ceramic Dental Crowns", value: "crowns_bridges" },
            { label: "Painless Wisdom Tooth Extraction", value: "tooth_extraction" },
            { label: "Cosmetic Veneers & Smile Designing", value: "smile_design" },
            { label: "Pediatric / Children Dental Care", value: "pediatric_dental" },
            { label: "Gum Therapy & Ultrasonic Scaling", value: "gum_scaling" },
            { label: "Complete & Partial Dentures", value: "dentures" },
          ],
        },
        {
          id: "dent_emergency",
          name: "emergencyAvailable",
          label: "24/7 / On-Call Emergency Dental Care",
          type: "switch",
          defaultValue: false,
        },
        {
          id: "dent_digital_xray",
          name: "digitalXRayOnsite",
          label: "In-House Digital X-Ray (RVG / OPG)",
          type: "switch",
          defaultValue: true,
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "dental_council_registration",
      label: "State Dental Council Registration Certificate",
      description: "Mandatory certificate of registration issued by the State Dental Council / DCI",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "degree_certificate",
      label: "BDS / MDS Degree Certificate",
      description: "Educational degree certificate from recognized dental college",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
