import { CategoryConfig } from "@/lib/onboarding/types";

export const doctorConfig: CategoryConfig = {
  id: "cat_doctor",
  slug: "doctor",
  name: "Doctor & Specialist Clinics",
  icon: "Stethoscope",
  description: "Specialist Physicians, Surgeons, Pediatricians, Gynecologists & Doctors",
  sections: [
    {
      id: "doctor_profile",
      title: "Doctor Profile & Credentials",
      description: "Medical qualifications, council registration, and specialty",
      fields: [
        {
          id: "doc_name",
          name: "doctorFullName",
          label: "Doctor Full Name",
          type: "text",
          required: true,
          placeholder: "e.g. Dr. Rajesh K. Gupta",
        },
        {
          id: "doc_specialty",
          name: "primarySpecialization",
          label: "Primary Medical Specialization",
          type: "select",
          required: true,
          options: [
            { label: "General Physician & Internal Medicine", value: "general_physician" },
            { label: "Cardiologist (Heart Specialist)", value: "cardiologist" },
            { label: "Dermatologist & Cosmetologist (Skin & Hair)", value: "dermatologist" },
            { label: "Pediatrician (Child Specialist)", value: "pediatrician" },
            { label: "Gynecologist & Obstetrician (Women's Health)", value: "gynecologist" },
            { label: "Orthopedic Surgeon (Bone & Joint)", value: "orthopedic" },
            { label: "ENT Specialist (Ear, Nose, Throat)", value: "ent" },
            { label: "Ophthalmologist (Eye Surgeon)", value: "ophthalmologist" },
            { label: "Neurologist / Neurosurgeon", value: "neurologist" },
            { label: "Gastroenterologist (Digestive & Liver)", value: "gastroenterologist" },
            { label: "Pulmonologist / Chest Physician", value: "pulmonologist" },
            { label: "Psychiatrist & Mental Health", value: "psychiatrist" },
            { label: "Urologist & Andrologist", value: "urologist" },
            { label: "Nephrologist (Kidney Specialist)", value: "nephrologist" },
            { label: "Oncologist (Cancer Specialist)", value: "oncologist" },
            { label: "General & Laparoscopic Surgeon", value: "surgeon" },
            { label: "Physiotherapist & Rehab Specialist", value: "physiotherapist" },
            { label: "Ayurvedic Doctor (BAMS / MD)", value: "ayurveda" },
            { label: "Homeopathic Doctor (BHMS / MD)", value: "homeopathy" },
          ],
        },
        {
          id: "doc_qualifications",
          name: "medicalDegrees",
          label: "Medical Degrees & Qualifications",
          type: "text",
          required: true,
          placeholder: "e.g. MBBS, MD (Medicine), DM (Cardiology)",
        },
        {
          id: "doc_reg_number",
          name: "medicalCouncilRegNumber",
          label: "Medical Council Registration Number",
          type: "text",
          required: true,
          placeholder: "e.g. MCI-2015-48921 / UPMC-65231",
        },
        {
          id: "doc_experience",
          name: "experienceYears",
          label: "Years of Clinical Practice",
          type: "number",
          required: true,
          placeholder: "e.g. 15",
          validation: { min: 0, max: 65 },
        },
      ],
    },
    {
      id: "consultation_details",
      title: "Consultation Modes & Fees",
      description: "Consultation channels, clinic hours, and fee structure",
      fields: [
        {
          id: "doc_modes",
          name: "consultationModes",
          label: "Available Consultation Modes",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "In-Clinic OPD Consultation", value: "in_clinic" },
            { label: "Online Video Tele-Consultation", value: "video" },
            { label: "Home Visit for Elderly / Urgent Care", value: "home_visit" },
          ],
        },
        {
          id: "doc_clinic_fee",
          name: "inClinicFee",
          label: "In-Clinic Consultation Fee (₹)",
          type: "currency",
          required: true,
          placeholder: "e.g. 500",
          validation: { min: 0 },
        },
        {
          id: "doc_video_fee",
          name: "videoConsultationFee",
          label: "Video Consultation Fee (₹)",
          type: "currency",
          placeholder: "e.g. 400",
          visibleWhen: {
            field: "categoryData.consultationModes",
            operator: "includes",
            value: "video",
          },
        },
        {
          id: "doc_languages",
          name: "languagesSpoken",
          label: "Languages Spoken",
          type: "text",
          placeholder: "e.g. Hindi, English, Braj Bhasha",
        },
        {
          id: "doc_hospital_affiliations",
          name: "hospitalAttachments",
          label: "Hospital / Visiting Consultant Attachments",
          type: "text",
          placeholder: "e.g. Visiting Consultant at Niyati Hospital, Mathura",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "medical_council_certificate",
      label: "State / National Medical Council Registration Certificate",
      description: "Mandatory valid registration certificate from State Medical Council or NMC",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "medical_degree_certificate",
      label: "MBBS / MD / Post-Graduate Degree Certificate",
      description: "Copy of highest medical qualification degree",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
