import { CategoryConfig } from "@/lib/onboarding/types";

export const hospitalConfig: CategoryConfig = {
  id: "cat_hospital",
  slug: "hospital",
  name: "Hospital & Healthcare",
  icon: "Cross",
  description: "General, Multi-Specialty & Super-Specialty Hospitals, ICUs & Trauma Centers",
  sections: [
    {
      id: "hospital_overview",
      title: "Hospital Overview & Capacity",
      description: "Hospital classification, in-patient bed strength, and critical care units",
      fields: [
        {
          id: "hosp_type",
          name: "hospitalType",
          label: "Hospital Classification",
          type: "select",
          required: true,
          options: [
            { label: "Multi-Specialty Hospital", value: "multi_specialty" },
            { label: "Super-Specialty Care Hospital", value: "super_specialty" },
            { label: "General & Community Hospital", value: "general" },
            { label: "Maternity, Gynecology & Women's Hospital", value: "maternity" },
            { label: "Pediatric & Children's Hospital", value: "children" },
            { label: "Cardiac Care & Heart Institute", value: "cardiac" },
            { label: "Cancer & Oncology Hospital", value: "cancer" },
            { label: "Eye (Ophthalmology) Hospital", value: "eye" },
            { label: "Orthopedic & Joint Replacement Hospital", value: "orthopedic" },
            { label: "Trauma & Emergency Center", value: "trauma" },
          ],
        },
        {
          id: "hosp_total_beds",
          name: "totalBedCapacity",
          label: "Total In-Patient Bed Capacity",
          type: "number",
          required: true,
          placeholder: "e.g. 150",
          validation: { min: 5, max: 5000 },
        },
        {
          id: "hosp_icu_beds",
          name: "icuBedCapacity",
          label: "Total ICU / Critical Care Beds",
          type: "number",
          required: true,
          placeholder: "e.g. 25",
          validation: { min: 0 },
        },
        {
          id: "hosp_ot_count",
          name: "operationTheatresCount",
          label: "Number of Modular Operation Theatres (OT)",
          type: "number",
          placeholder: "e.g. 4",
          validation: { min: 0 },
        },
        {
          id: "hosp_nicu_available",
          name: "nicuPicuAvailable",
          label: "NICU / PICU (Neonatal & Pediatric ICU) Available",
          type: "switch",
          defaultValue: true,
        },
      ],
    },
    {
      id: "emergency_services",
      title: "Emergency Services & 24/7 Units",
      description: "Critical emergency infrastructure and around-the-clock facilities",
      fields: [
        {
          id: "hosp_emergency_facilities",
          name: "emergencyInfrastructure",
          label: "24/7 Essential Medical Facilities",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "24/7 Emergency & Trauma Casualty Department", value: "emergency_trauma" },
            { label: "24/7 In-House Pharmacy / Chemist", value: "pharmacy" },
            { label: "24/7 Diagnostic Pathology & Blood Testing Lab", value: "pathology_lab" },
            { label: "24/7 Radiology (X-Ray, Ultrasound, CT Scan, MRI)", value: "radiology" },
            { label: "Licensed Blood Bank / Storage Center on Campus", value: "blood_bank" },
            { label: "24/7 Advanced Cardiac Life Support (ACLS) Ambulance", value: "ambulance" },
            { label: "Dialysis Unit with Multiple Stations", value: "dialysis" },
          ],
        },
      ],
    },
    {
      id: "specialties_insurance",
      title: "Medical Departments & Insurance",
      description: "Clinical departments, cashless TPA, and accreditation status",
      fields: [
        {
          id: "hosp_specialties",
          name: "departments",
          label: "Key Medical Departments & Specialties",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "Cardiology & Cath Lab", value: "cardiology" },
            { label: "Neurology & Neurosurgery", value: "neurology" },
            { label: "Orthopedics & Joint Replacement", value: "orthopedics" },
            { label: "General & Laparoscopic Surgery", value: "surgery" },
            { label: "Obstetrics & Gynecology", value: "gynecology" },
            { label: "Pediatrics & Neonatology", value: "pediatrics" },
            { label: "Nephrology & Urology", value: "nephro_uro" },
            { label: "Gastroenterology & Endoscopy", value: "gastroenterology" },
            { label: "Pulmonology & Chest Diseases", value: "pulmonology" },
            { label: "Oncology & Chemotherapy", value: "oncology" },
            { label: "Dermatology & Cosmetology", value: "dermatology" },
            { label: "ENT (Ear, Nose, Throat)", value: "ent" },
            { label: "Ophthalmology (Eye Care)", value: "ophthalmology" },
            { label: "Dental Surgery", value: "dental" },
          ],
        },
        {
          id: "hosp_cashless_insurance",
          name: "cashlessInsuranceAccepted",
          label: "Cashless Mediclaim / Insurance TPA Tie-Ups Available",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "hosp_ayushman_bharat",
          name: "ayushmanBharatEmpanelled",
          label: "Ayushman Bharat (PM-JAY) Scheme Empanelled",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "hosp_accreditation",
          name: "accreditation",
          label: "Hospital Accreditations",
          type: "checkbox_group",
          options: [
            { label: "NABH Accredited (National Accreditation Board for Hospitals)", value: "nabh" },
            { label: "NABL Accredited Diagnostic Laboratory", value: "nabl" },
            { label: "ISO 9001:2015 Certified Healthcare", value: "iso" },
          ],
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "clinical_establishment_registration",
      label: "Clinical Establishment Act Registration Certificate",
      description: "Mandatory state health department registration certificate for hospital operations",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "pollution_control_noc",
      label: "Bio-Medical Waste Management & Pollution NOC",
      description: "State Pollution Control Board authorization for bio-medical waste",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "fire_safety_noc",
      label: "Fire Safety Clearance Certificate (NOC)",
      description: "Fire department compliance certificate for hospital building",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
