import { CategoryConfig, FieldConfig } from "@/lib/onboarding/types";

const ROOM_TYPE_OPTIONS = [
  { label: "Standard / Primary Room", value: "standard", description: "Standard single/double room" },
  { label: "Deluxe Room", value: "deluxe", description: "Upgraded comfort with extra amenities" },
  { label: "Luxury / Super Deluxe Room", value: "luxury", description: "Premium interiors & spacious layout" },
  { label: "Suite", value: "suite", description: "Separate living & sleeping areas" },
  { label: "Family Room", value: "family", description: "Multiple beds for families & groups" },
  { label: "Executive Room", value: "executive", description: "Business-tailored with work desk" },
  { label: "Premium Room", value: "premium", description: "Top-tier furnishings & views" },
  { label: "Presidential Suite", value: "presidential", description: "Grand master suite experience" },
];

function createRoomTypeGroup(roomKey: string, roomLabel: string): FieldConfig {
  return {
    id: `hotel_${roomKey}_group`,
    name: `${roomKey}Details`,
    label: `${roomLabel} Configuration`,
    description: `Configure rates, occupancy, and details for ${roomLabel}`,
    type: "group",
    visibleWhen: {
      field: "categoryData.roomTypes",
      operator: "includes",
      value: roomKey,
    },
    fields: [
      {
        id: `hotel_${roomKey}_count`,
        name: "roomsCount",
        label: "Number of Rooms",
        type: "number",
        required: true,
        placeholder: "e.g. 10",
        validation: { min: 1, max: 1000 },
      },
      {
        id: `hotel_${roomKey}_price`,
        name: "pricePerNight",
        label: "Price Per Night (₹)",
        type: "currency",
        required: true,
        placeholder: "e.g. 3500",
        validation: { min: 100 },
      },
      {
        id: `hotel_${roomKey}_occupancy`,
        name: "maxOccupancy",
        label: "Max Occupancy (Guests)",
        type: "number",
        required: true,
        placeholder: "e.g. 2",
        validation: { min: 1, max: 20 },
      },
      {
        id: `hotel_${roomKey}_bed`,
        name: "bedType",
        label: "Bed Type",
        type: "select",
        required: true,
        options: [
          { label: "Single Bed", value: "single" },
          { label: "Double Bed", value: "double" },
          { label: "Queen Bed", value: "queen" },
          { label: "King Bed", value: "king" },
          { label: "Twin Beds", value: "twin" },
        ],
      },
      {
        id: `hotel_${roomKey}_size`,
        name: "roomSizeSqFt",
        label: "Room Size (sq. ft.)",
        type: "number",
        placeholder: "e.g. 280",
      },
      {
        id: `hotel_${roomKey}_ac`,
        name: "hasAC",
        label: "Air Conditioning",
        type: "switch",
        defaultValue: true,
      },
      {
        id: `hotel_${roomKey}_bathroom`,
        name: "hasAttachedBathroom",
        label: "Attached Bathroom",
        type: "switch",
        defaultValue: true,
      },
      {
        id: `hotel_${roomKey}_balcony`,
        name: "hasBalcony",
        label: "Private Balcony",
        type: "switch",
        defaultValue: false,
      },
      {
        id: `hotel_${roomKey}_tv`,
        name: "hasTV",
        label: "LED / Smart TV",
        type: "switch",
        defaultValue: true,
      },
      {
        id: `hotel_${roomKey}_wifi`,
        name: "hasWifi",
        label: "High-Speed Wi-Fi in Room",
        type: "switch",
        defaultValue: true,
      },
      {
        id: `hotel_${roomKey}_amenities`,
        name: "roomAmenities",
        label: "Room Inclusions & Amenities",
        type: "checkbox_group",
        options: [
          { label: "Tea / Coffee Maker", value: "tea_coffee_maker" },
          { label: "Mini Refrigerator / Bar", value: "mini_bar" },
          { label: "In-Room Electronic Safe", value: "safe" },
          { label: "Hair Dryer", value: "hair_dryer" },
          { label: "Iron & Board", value: "iron" },
          { label: "Dedicated Work Desk", value: "work_desk" },
          { label: "24/7 Room Service", value: "room_service" },
          { label: "Bathrobes & Slippers", value: "bathrobes" },
        ],
      },
      {
        id: `hotel_${roomKey}_image`,
        name: "roomImage",
        label: "Room Photo",
        type: "image",
        description: "Upload a high-quality photo representing this room category",
      },
    ],
  };
}

export const hotelConfig: CategoryConfig = {
  id: "cat_hotel",
  slug: "hotel",
  name: "Hotel & Hospitality",
  icon: "Hotel",
  description: "Hotels, Resorts, Haveli, Homestays, Guest Houses & Lodging",
  sections: [
    {
      id: "property_overview",
      title: "Property Overview",
      description: "Basic property categorization, star rating, and room capacity",
      fields: [
        {
          id: "hotel_property_type",
          name: "propertyType",
          label: "Property Type",
          type: "select",
          required: true,
          options: [
            { label: "Hotel", value: "hotel" },
            { label: "Resort", value: "resort" },
            { label: "Boutique Hotel", value: "boutique_hotel" },
            { label: "Business Hotel", value: "business_hotel" },
            { label: "Budget Hotel", value: "budget_hotel" },
            { label: "Luxury Hotel", value: "luxury_hotel" },
            { label: "Heritage Hotel / Haveli", value: "heritage_haveli" },
            { label: "Guest House", value: "guest_house" },
            { label: "Homestay", value: "homestay" },
            { label: "Bed & Breakfast", value: "bed_and_breakfast" },
            { label: "Hostel / Backpackers", value: "hostel" },
            { label: "Motel", value: "motel" },
            { label: "Lodge", value: "lodge" },
            { label: "Farm Stay", value: "farm_stay" },
            { label: "Villa", value: "villa" },
            { label: "Serviced Apartment", value: "serviced_apartment" },
            { label: "Eco Resort", value: "eco_resort" },
            { label: "Wedding Resort", value: "wedding_resort" },
            { label: "Wellness / Spa Resort", value: "spa_resort" },
          ],
        },
        {
          id: "hotel_star_rating",
          name: "starRating",
          label: "Star / Quality Rating",
          type: "select",
          options: [
            { label: "5 Star Luxury", value: "5_star" },
            { label: "4 Star Premium", value: "4_star" },
            { label: "3 Star Comfort", value: "3_star" },
            { label: "2 Star Standard", value: "2_star" },
            { label: "1 Star Basic", value: "1_star" },
            { label: "Govt. Approved / Unrated", value: "unrated" },
          ],
        },
        {
          id: "hotel_total_rooms",
          name: "totalRooms",
          label: "Total Number of Rooms in Property",
          type: "number",
          required: true,
          placeholder: "e.g. 45",
          validation: { min: 1, max: 2000 },
        },
      ],
    },
    {
      id: "room_types_selection",
      title: "Room Types Available",
      description: "Select all room categories available at your property to configure each",
      fields: [
        {
          id: "hotel_room_types",
          name: "roomTypes",
          label: "Select Room Categories",
          type: "checkbox_group",
          required: true,
          options: ROOM_TYPE_OPTIONS,
        },
        createRoomTypeGroup("standard", "Standard / Primary Room"),
        createRoomTypeGroup("deluxe", "Deluxe Room"),
        createRoomTypeGroup("luxury", "Luxury / Super Deluxe Room"),
        createRoomTypeGroup("suite", "Suite"),
        createRoomTypeGroup("family", "Family Room"),
        createRoomTypeGroup("executive", "Executive Room"),
        createRoomTypeGroup("premium", "Premium Room"),
        createRoomTypeGroup("presidential", "Presidential Suite"),
      ],
    },
    {
      id: "facilities_amenities",
      title: "Hotel Facilities & Amenities",
      description: "Highlight guest facilities and property features",
      fields: [
        {
          id: "hotel_facilities",
          name: "facilities",
          label: "Property Facilities",
          type: "checkbox_group",
          options: [
            { label: "Swimming Pool", value: "swimming_pool" },
            { label: "Multi-Cuisine Restaurant", value: "restaurant" },
            { label: "24/7 Room Service", value: "room_service" },
            { label: "Fitness Center / Gym", value: "gym" },
            { label: "Spa & Wellness Center", value: "spa" },
            { label: "Conference & Meeting Hall", value: "conference_hall" },
            { label: "Banquet Hall", value: "banquet_hall" },
            { label: "Grand Wedding Venue / Lawn", value: "wedding_venue" },
            { label: "Free Guest Parking", value: "parking" },
            { label: "High-Speed Wi-Fi", value: "wifi" },
            { label: "24/7 Power Backup", value: "power_backup" },
            { label: "24/7 Front Desk", value: "front_desk_247" },
            { label: "Elevator / Lift", value: "elevator" },
            { label: "CCTV Security Surveillance", value: "cctv" },
            { label: "Laundry & Dry Cleaning", value: "laundry" },
            { label: "Airport / Railway Station Pickup", value: "airport_pickup" },
          ],
        },
        {
          id: "hotel_pool_group",
          name: "poolDetails",
          label: "Swimming Pool Details",
          type: "group",
          visibleWhen: {
            field: "categoryData.facilities",
            operator: "includes",
            value: "swimming_pool",
          },
          fields: [
            {
              id: "hotel_pool_type",
              name: "poolType",
              label: "Pool Type",
              type: "select",
              options: [
                { label: "Outdoor Pool", value: "outdoor" },
                { label: "Indoor Temperature Controlled", value: "indoor" },
                { label: "Infinity Pool", value: "infinity" },
                { label: "Rooftop Pool", value: "rooftop" },
              ],
            },
            {
              id: "hotel_kids_pool",
              name: "kidsPoolAvailable",
              label: "Separate Kids / Wading Pool Available",
              type: "switch",
              defaultValue: true,
            },
            {
              id: "hotel_pool_timings",
              name: "poolTimings",
              label: "Pool Operating Timings",
              type: "text",
              placeholder: "e.g. 7:00 AM - 8:00 PM",
            },
          ],
        },
        {
          id: "hotel_conference_group",
          name: "conferenceDetails",
          label: "Conference Hall Details",
          type: "group",
          visibleWhen: {
            field: "categoryData.facilities",
            operator: "includes",
            value: "conference_hall",
          },
          fields: [
            {
              id: "hotel_conf_halls_count",
              name: "numberOfHalls",
              label: "Number of Conference Halls",
              type: "number",
              placeholder: "e.g. 2",
              validation: { min: 1 },
            },
            {
              id: "hotel_conf_max_capacity",
              name: "maxSeatingCapacity",
              label: "Maximum Seating Capacity (Pax)",
              type: "number",
              placeholder: "e.g. 200",
              validation: { min: 10 },
            },
          ],
        },
        {
          id: "hotel_banquet_group",
          name: "banquetDetails",
          label: "Banquet Hall Details",
          type: "group",
          visibleWhen: {
            field: "categoryData.facilities",
            operator: "includes",
            value: "banquet_hall",
          },
          fields: [
            {
              id: "hotel_banquet_capacity",
              name: "banquetCapacity",
              label: "Banquet Guest Capacity (Pax)",
              type: "number",
              placeholder: "e.g. 500",
              validation: { min: 20 },
            },
            {
              id: "hotel_banquet_catering",
              name: "cateringPolicy",
              label: "Catering Policy",
              type: "select",
              options: [
                { label: "In-House Catering Only", value: "in_house_only" },
                { label: "Outside Catering Allowed", value: "outside_allowed" },
                { label: "Both In-House & Outside Catering", value: "both" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "policies_timings",
      title: "Hotel Policies & Rules",
      description: "Guest check-in/out policies, couple friendliness, and restrictions",
      fields: [
        {
          id: "hotel_checkin_time",
          name: "checkInTime",
          label: "Standard Check-In Time",
          type: "time",
          required: true,
          defaultValue: "12:00",
        },
        {
          id: "hotel_checkout_time",
          name: "checkOutTime",
          label: "Standard Check-Out Time",
          type: "time",
          required: true,
          defaultValue: "11:00",
        },
        {
          id: "hotel_cancellation",
          name: "cancellationPolicy",
          label: "Cancellation Policy",
          type: "select",
          required: true,
          options: [
            { label: "Flexible (Full refund up to 24 hrs before check-in)", value: "flexible" },
            { label: "Moderate (Full refund up to 5 days before check-in)", value: "moderate" },
            { label: "Strict (50% refund up to 7 days before check-in)", value: "strict" },
            { label: "Non-Refundable", value: "non_refundable" },
          ],
        },
        {
          id: "hotel_couple_friendly",
          name: "coupleFriendly",
          label: "Couple Friendly (Unmarried couples allowed with valid ID)",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "hotel_family_friendly",
          name: "familyFriendly",
          label: "Family Friendly Property",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "hotel_pet_friendly",
          name: "petFriendly",
          label: "Pet Friendly (Pets allowed)",
          type: "switch",
          defaultValue: false,
        },
        {
          id: "hotel_smoking_policy",
          name: "smokingPolicy",
          label: "Smoking Policy",
          type: "select",
          options: [
            { label: "100% Non-Smoking Property", value: "non_smoking" },
            { label: "Designated Smoking Areas Only", value: "designated_areas" },
            { label: "Smoking Allowed in Selected Rooms", value: "smoking_rooms" },
          ],
        },
        {
          id: "hotel_child_policy",
          name: "childPolicy",
          label: "Child & Extra Bed Policy",
          type: "textarea",
          placeholder: "e.g. Children below 6 years stay free without extra bed. Extra mattress available at ₹500/night.",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "business_registration",
      label: "Hotel Business Registration / Trade License",
      description: "Municipal trade license or tourism department registration certificate",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "gst_certificate",
      label: "GST Registration Certificate",
      description: "GSTIN registration certificate for hotel operations",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "property_ownership_or_lease",
      label: "Property Ownership Deed or Lease Agreement",
      description: "Proof of property ownership or registered lease agreement",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "fire_noc",
      label: "Fire Safety NOC",
      description: "Fire department clearance certificate (if applicable for property size)",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
