import { CategoryConfig } from "@/lib/onboarding/types";

export const loanConfig: CategoryConfig = {
  id: "cat_loan",
  slug: "loan",
  name: "Loans & Financial Services",
  icon: "Banknote",
  description: "Personal, Home, Business, MSME, Vehicle & Mortgage Loan Providers",
  sections: [
    {
      id: "loan_overview",
      title: "Financial Service Overview",
      description: "Entity type and loan products provided",
      fields: [
        {
          id: "loan_provider_type",
          name: "providerType",
          label: "Entity Type",
          type: "select",
          required: true,
          options: [
            { label: "RBI Registered NBFC", value: "nbfc" },
            { label: "Bank Direct Selling Agent (DSA)", value: "dsa" },
            { label: "Cooperative Bank / Credit Society", value: "cooperative" },
            { label: "Certified Financial Loan Consultant", value: "consultant" },
          ],
        },
        {
          id: "loan_types_offered",
          name: "loanTypes",
          label: "Loan Products Offered",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "Personal Loan", value: "personal_loan" },
            { label: "Home Loan / Housing Finance", value: "home_loan" },
            { label: "Business & MSME Loan", value: "business_loan" },
            { label: "Loan Against Property (LAP)", value: "lap" },
            { label: "Vehicle / Car / Auto Loan", value: "vehicle_loan" },
            { label: "Education / Study Loan", value: "education_loan" },
            { label: "Instant Gold Loan", value: "gold_loan" },
            { label: "Machinery & Equipment Loan", value: "machinery_loan" },
            { label: "Working Capital / Overdraft Limit", value: "working_capital" },
          ],
        },
      ],
    },
    {
      id: "loan_terms",
      title: "Loan Terms & Limits",
      description: "Amount ranges, interest rates, and repayment tenures",
      fields: [
        {
          id: "loan_min_amount",
          name: "minLoanAmount",
          label: "Minimum Loan Amount (₹)",
          type: "currency",
          required: true,
          placeholder: "e.g. 50000",
          validation: { min: 1000 },
        },
        {
          id: "loan_max_amount",
          name: "maxLoanAmount",
          label: "Maximum Loan Amount (₹)",
          type: "currency",
          required: true,
          placeholder: "e.g. 50000000",
          validation: { min: 10000 },
        },
        {
          id: "loan_min_interest",
          name: "minInterestRateAPR",
          label: "Starting Interest Rate (APR % p.a.)",
          type: "number",
          required: true,
          placeholder: "e.g. 8.5",
          validation: { min: 1, max: 40 },
        },
        {
          id: "loan_max_tenure",
          name: "maxTenureYears",
          label: "Maximum Repayment Tenure (Years)",
          type: "number",
          required: true,
          placeholder: "e.g. 20",
          validation: { min: 1, max: 35 },
        },
        {
          id: "loan_processing_fee",
          name: "processingFeePercentage",
          label: "Processing Fee (% of loan amount)",
          type: "number",
          placeholder: "e.g. 1.0",
        },
      ],
    },
    {
      id: "eligibility_docs",
      title: "Eligibility & Requirements",
      description: "Applicant eligibility criteria and document verification",
      fields: [
        {
          id: "loan_min_income",
          name: "minMonthlyIncome",
          label: "Minimum Monthly Income Required (₹)",
          type: "currency",
          placeholder: "e.g. 25000",
        },
        {
          id: "loan_employment_types",
          name: "eligibleEmploymentTypes",
          label: "Eligible Employment Categories",
          type: "checkbox_group",
          options: [
            { label: "Salaried Employees (Govt. & Private)", value: "salaried" },
            { label: "Self-Employed Professionals (Doctors, CA, Lawyers)", value: "self_employed_pro" },
            { label: "Self-Employed Business Owners & Traders", value: "self_employed_biz" },
            { label: "Farmers & Agricultural Income Earners", value: "agriculturists" },
          ],
        },
        {
          id: "loan_collateral_policy",
          name: "collateralRequired",
          label: "Collateral / Security Requirement",
          type: "select",
          options: [
            { label: "Zero Collateral (Unsecured Loans)", value: "unsecured" },
            { label: "Secured by Property / Gold / Fixed Deposits", value: "secured" },
            { label: "Both Secured & Unsecured Options Available", value: "both" },
          ],
        },
        {
          id: "loan_app_process",
          name: "applicationProcessDetails",
          label: "Application Process Overview",
          type: "textarea",
          placeholder: "e.g. Fast approval within 48 hours. Minimal documentation with doorstep pickup service in Mathura & Vrindavan.",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "nbfc_or_dsa_authorization",
      label: "NBFC Certificate or Bank DSA Authorization Letter",
      description: "Valid certificate of registration from RBI or bank agency authorization agreement",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "business_pan_gst",
      label: "Business PAN Card / GST Registration",
      description: "Identity verification of the financial enterprise or agency",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
