import { CategoryConfig } from "@/lib/onboarding/types";

export const propertyConfig: CategoryConfig = {
  id: "cat_property",
  slug: "property",
  name: "Property & Real Estate",
  icon: "Building",
  description: "Flats, Villas, Plots, Commercial Shops, Offices, PG & Lands",
  sections: [
    {
      id: "property_basic_info",
      title: "Property & Listing Details",
      description: "Listing purpose and property classification",
      fields: [
        {
          id: "prop_purpose",
          name: "listingPurpose",
          label: "Listing Purpose",
          type: "select",
          required: true,
          options: [
            { label: "For Sale (Buy Property)", value: "sale" },
            { label: "For Rent / Lease", value: "rent" },
            { label: "Paying Guest (PG) / Co-living", value: "pg" },
            { label: "Commercial Lease", value: "commercial_lease" },
          ],
        },
        {
          id: "prop_type",
          name: "propertyType",
          label: "Property Category",
          type: "select",
          required: true,
          options: [
            { label: "Apartment / Flat", value: "apartment" },
            { label: "Independent Villa / Kothi", value: "villa" },
            { label: "Independent House", value: "house" },
            { label: "Builder Floor", value: "builder_floor" },
            { label: "Studio Apartment / 1 RK", value: "studio" },
            { label: "Luxury Penthouse", value: "penthouse" },
            { label: "Farmhouse / Country Estate", value: "farmhouse" },
            { label: "Residential Plot / Land", value: "residential_plot" },
            { label: "Commercial Plot / Land", value: "commercial_plot" },
            { label: "Agricultural Land / Farm", value: "agricultural_land" },
            { label: "Commercial Shop / Retail", value: "commercial_shop" },
            { label: "Commercial Office Space", value: "commercial_office" },
            { label: "Showroom Space", value: "showroom" },
            { label: "Warehouse / Godown", value: "warehouse" },
            { label: "PG (Paying Guest) Accommodation", value: "pg_coliving" },
            { label: "Shared Co-Working Space", value: "coworking" },
          ],
        },
        {
          id: "prop_price",
          name: "expectedPrice",
          label: "Expected Price / Monthly Rent (₹)",
          type: "currency",
          required: true,
          placeholder: "e.g. 4500000",
          validation: { min: 1000 },
        },
      ],
    },
    {
      id: "residential_specs",
      title: "Residential Property Specifications",
      description: "Bedrooms, bathrooms, furnishing, and floor details",
      visibleWhen: {
        field: "categoryData.propertyType",
        operator: "includes",
        value: "apartment",
      },
      fields: [
        {
          id: "res_bhk",
          name: "bedroomsBHK",
          label: "Configuration (BHK)",
          type: "select",
          required: true,
          options: [
            { label: "1 BHK", value: "1_bhk" },
            { label: "2 BHK", value: "2_bhk" },
            { label: "3 BHK", value: "3_bhk" },
            { label: "4 BHK", value: "4_bhk" },
            { label: "5+ BHK / Penthouse", value: "5_plus_bhk" },
            { label: "1 RK (Room Kitchen)", value: "1_rk" },
          ],
        },
        {
          id: "res_bathrooms",
          name: "bathrooms",
          label: "Number of Bathrooms",
          type: "number",
          placeholder: "e.g. 2",
          validation: { min: 1, max: 10 },
        },
        {
          id: "res_furnishing",
          name: "furnishingStatus",
          label: "Furnishing Status",
          type: "select",
          required: true,
          options: [
            { label: "Fully Furnished", value: "fully_furnished" },
            { label: "Semi-Furnished (Wardrobes, Modular Kitchen)", value: "semi_furnished" },
            { label: "Unfurnished", value: "unfurnished" },
          ],
        },
        {
          id: "res_carpet_area",
          name: "carpetAreaSqFt",
          label: "Carpet Area (sq. ft.)",
          type: "number",
          required: true,
          placeholder: "e.g. 1150",
          validation: { min: 50 },
        },
        {
          id: "res_floor_no",
          name: "floorNumber",
          label: "Floor Number",
          type: "number",
          placeholder: "e.g. 3 (0 for Ground)",
        },
        {
          id: "res_total_floors",
          name: "totalFloors",
          label: "Total Floors in Building",
          type: "number",
          placeholder: "e.g. 12",
        },
        {
          id: "res_parking",
          name: "parkingSpots",
          label: "Reserved Parking Available",
          type: "select",
          options: [
            { label: "1 Covered Car Parking", value: "1_covered" },
            { label: "2 Covered Car Parking", value: "2_covered" },
            { label: "Open Car Parking", value: "open" },
            { label: "Two-Wheeler Only", value: "two_wheeler" },
            { label: "No Parking", value: "none" },
          ],
        },
      ],
    },
    {
      id: "plot_specs",
      title: "Plot / Land Specifications",
      description: "Land dimensions, zoning, and boundary details",
      visibleWhen: {
        field: "categoryData.propertyType",
        operator: "includes",
        value: "plot",
      },
      fields: [
        {
          id: "plot_area",
          name: "plotAreaSqYards",
          label: "Plot Area (sq. yards / gaj)",
          type: "number",
          required: true,
          placeholder: "e.g. 200",
          validation: { min: 10 },
        },
        {
          id: "plot_dimensions",
          name: "dimensions",
          label: "Plot Dimensions (Length x Width in ft)",
          type: "text",
          placeholder: "e.g. 30 x 60 ft",
        },
        {
          id: "plot_facing",
          name: "facingDirection",
          label: "Plot Facing Direction",
          type: "select",
          options: [
            { label: "East Facing (Auspicious)", value: "east" },
            { label: "North Facing (Auspicious)", value: "north" },
            { label: "North-East Facing (Ishan)", value: "north_east" },
            { label: "West Facing", value: "west" },
            { label: "South Facing", value: "south" },
          ],
        },
        {
          id: "plot_boundary",
          name: "hasBoundaryWall",
          label: "Constructed Boundary Wall Present",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "plot_gated",
          name: "inGatedColony",
          label: "Located in Gated Colony / Society",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "plot_road_width",
          name: "frontRoadWidthFt",
          label: "Width of Facing Road (ft)",
          type: "number",
          placeholder: "e.g. 30",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "property_registry_or_khatauni",
      label: "Registry Document / Khatauni / Allotment Letter",
      description: "Document establishing title and ownership rights of the property",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "rera_registration",
      label: "RERA Registration Certificate (If Builder/Project)",
      description: "State Real Estate Regulatory Authority certificate for new projects",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
