import { CategoryConfig } from "@/lib/onboarding/types";

export const restaurantConfig: CategoryConfig = {
  id: "cat_restaurant",
  slug: "restaurant",
  name: "Restaurant & Food",
  icon: "Utensils",
  description: "Restaurants, Cafes, Dhabas, Bakeries, Sweet Shops & Cloud Kitchens",
  sections: [
    {
      id: "restaurant_overview",
      title: "Establishment Overview",
      description: "Dining format, dining style, and capacity details",
      fields: [
        {
          id: "rest_type",
          name: "restaurantType",
          label: "Establishment Type",
          type: "select",
          required: true,
          options: [
            { label: "Fine Dining Restaurant", value: "fine_dining" },
            { label: "Casual Dining / Family Restaurant", value: "casual_dining" },
            { label: "Cafe & Coffee Shop", value: "cafe" },
            { label: "Fast Food & Quick Service (QSR)", value: "fast_food" },
            { label: "Bakery & Confectionery", value: "bakery" },
            { label: "Traditional Sweet Shop (Mithai)", value: "sweet_shop" },
            { label: "Authentic Dhaba", value: "dhaba" },
            { label: "Food Court Outlet", value: "food_court" },
            { label: "Food Truck / Kiosk", value: "food_truck" },
            { label: "Cloud Kitchen / Delivery Only", value: "cloud_kitchen" },
            { label: "Pure Vegetarian Restaurant", value: "pure_veg" },
            { label: "Vegan Restaurant", value: "vegan" },
            { label: "Bar & Restaurant / Pub", value: "bar_restaurant" },
          ],
        },
        {
          id: "rest_avg_cost",
          name: "averageCostForTwo",
          label: "Approximate Cost for Two (₹)",
          type: "currency",
          required: true,
          placeholder: "e.g. 600",
          validation: { min: 50 },
        },
        {
          id: "rest_seating_capacity",
          name: "seatingCapacity",
          label: "Seating Capacity (Guests)",
          type: "number",
          placeholder: "e.g. 60",
          validation: { min: 0, max: 2000 },
        },
      ],
    },
    {
      id: "cuisines_dietary",
      title: "Cuisines & Dietary Options",
      description: "Select all cuisines and dietary offerings served",
      fields: [
        {
          id: "rest_cuisines",
          name: "cuisines",
          label: "Cuisines Served",
          type: "checkbox_group",
          required: true,
          options: [
            { label: "North Indian", value: "north_indian" },
            { label: "South Indian", value: "south_indian" },
            { label: "Chinese & Pan-Asian", value: "chinese" },
            { label: "Italian & Pizza / Pasta", value: "italian" },
            { label: "Continental & European", value: "continental" },
            { label: "Mughlai", value: "mughlai" },
            { label: "Punjabi", value: "punjabi" },
            { label: "Rajasthani & Marwari", value: "rajasthani" },
            { label: "Bengali", value: "bengali" },
            { label: "Braj & Mathura Traditional Sweets", value: "braj_traditional" },
            { label: "Chaat & Street Food", value: "street_food" },
            { label: "Bakery & Desserts", value: "desserts" },
            { label: "Beverages & Mocktails", value: "beverages" },
          ],
        },
        {
          id: "rest_is_pure_veg",
          name: "isPureVeg",
          label: "100% Pure Vegetarian Kitchen (No Non-Veg)",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "rest_jain_food",
          name: "jainFoodAvailable",
          label: "Jain Food / No Onion & Garlic Option Available",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "rest_halal_food",
          name: "halalAvailable",
          label: "Halal Certified Meat Available",
          type: "switch",
          defaultValue: false,
          visibleWhen: {
            field: "categoryData.isPureVeg",
            operator: "is_false",
          },
        },
      ],
    },
    {
      id: "services_features",
      title: "Services & Features",
      description: "Dining formats, delivery, and entertainment options",
      fields: [
        {
          id: "rest_services",
          name: "services",
          label: "Service Offerings",
          type: "checkbox_group",
          options: [
            { label: "Dine-In Seating", value: "dine_in" },
            { label: "Takeaway / Parcel", value: "takeaway" },
            { label: "Direct Home Delivery", value: "home_delivery" },
            { label: "Outdoor / Open Air Seating", value: "outdoor_seating" },
            { label: "Table Reservation Available", value: "table_reservation" },
            { label: "Catering for Events / Parties", value: "catering" },
            { label: "Private Dining Area / Party Hall", value: "private_dining" },
          ],
        },
        {
          id: "rest_has_ac",
          name: "airConditioned",
          label: "Air Conditioned Dining Area",
          type: "switch",
          defaultValue: true,
        },
        {
          id: "rest_has_wifi",
          name: "freeWifi",
          label: "Free Customer Wi-Fi",
          type: "switch",
          defaultValue: false,
        },
        {
          id: "rest_live_music",
          name: "liveMusic",
          label: "Live Music / Entertainment",
          type: "switch",
          defaultValue: false,
        },
        {
          id: "rest_valet_parking",
          name: "valetParking",
          label: "Valet / Dedicated Parking",
          type: "switch",
          defaultValue: false,
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "fssai_license",
      label: "FSSAI Food Safety License / Registration",
      description: "Mandatory Food Safety and Standards Authority of India certificate",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "gst_certificate",
      label: "GST Registration Certificate",
      description: "GSTIN registration certificate for restaurant billing",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "health_trade_license",
      label: "Municipal Health & Trade License",
      description: "Local municipal corporation health/eating house license",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
