import { CategoryConfig } from "@/lib/onboarding/types";

export const schoolConfig: CategoryConfig = {
  id: "cat_school",
  slug: "school",
  name: "School & Preschool",
  icon: "School",
  description: "Play Schools, CBSE, ICSE, State Board & Senior Secondary Schools",
  sections: [
    {
      id: "school_overview",
      title: "School Overview",
      description: "School type, educational board affiliation, and medium",
      fields: [
        {
          id: "sch_type",
          name: "schoolType",
          label: "School Category",
          type: "select",
          required: true,
          options: [
            { label: "Play School / Kindergarten / Daycare", value: "play_school" },
            { label: "Primary School (Nursery to 5th)", value: "primary" },
            { label: "Middle School (Class 1 to 8th)", value: "middle" },
            { label: "Secondary School (Class 1 to 10th)", value: "secondary" },
            { label: "Senior Secondary School (Class 1 to 12th)", value: "senior_secondary" },
            { label: "Boarding / Residential School", value: "boarding" },
          ],
        },
        {
          id: "sch_board",
          name: "boardAffiliation",
          label: "Board of Education",
          type: "select",
          required: true,
          options: [
            { label: "CBSE (Central Board of Secondary Education)", value: "cbse" },
            { label: "ICSE / ISC (CISCE)", value: "icse" },
            { label: "IB (International Baccalaureate)", value: "ib" },
            { label: "Cambridge International (IGCSE)", value: "cambridge" },
            { label: "UP State Board", value: "up_board" },
            { label: "Playgroup / Early Childhood Curriculum", value: "early_childhood" },
          ],
        },
        {
          id: "sch_medium",
          name: "mediumOfInstruction",
          label: "Medium of Instruction",
          type: "select",
          required: true,
          options: [
            { label: "English Medium", value: "english" },
            { label: "Hindi Medium", value: "hindi" },
            { label: "Bilingual (English & Hindi)", value: "bilingual" },
          ],
        },
        {
          id: "sch_classes",
          name: "classesOffered",
          label: "Classes / Grades Offered",
          type: "text",
          required: true,
          placeholder: "e.g. Nursery to 12th Standard",
        },
        {
          id: "sch_affiliation_no",
          name: "affiliationNumber",
          label: "Board Affiliation Number",
          type: "text",
          placeholder: "e.g. CBSE/AFF/2130456",
        },
        {
          id: "sch_annual_fee",
          name: "annualFeeRange",
          label: "Annual Tuition Fee (Approx. ₹)",
          type: "currency",
          placeholder: "e.g. 45000",
        },
      ],
    },
    {
      id: "school_infrastructure",
      title: "Campus Infrastructure & Activities",
      description: "Classroom technology, sports facilities, and transport services",
      fields: [
        {
          id: "sch_facilities",
          name: "schoolFacilities",
          label: "School Facilities",
          type: "checkbox_group",
          options: [
            { label: "Smart Interactive Classrooms", value: "smart_classes" },
            { label: "Composite Science & Robotics Labs", value: "science_labs" },
            { label: "Air Conditioned Computer Lab", value: "computer_lab" },
            { label: "Comprehensive Library & Reading Room", value: "library" },
            { label: "Large Sports Playground & Track", value: "sports_ground" },
            { label: "GPS-Enabled School Bus Fleet", value: "school_bus" },
            { label: "24/7 CCTV Monitored Campus", value: "cctv" },
            { label: "Medical Room / First Aid Nurse", value: "infirmary" },
            { label: "Music, Dance & Fine Arts Studio", value: "arts_studio" },
            { label: "Hygienic Cafeteria", value: "cafeteria" },
            { label: "Swimming Pool for Students", value: "swimming_pool" },
          ],
        },
        {
          id: "sch_admission_process",
          name: "admissionDetails",
          label: "Admission Process & Age Criteria",
          type: "textarea",
          placeholder: "e.g. Minimum age 3+ years for Nursery as of March 31. Direct admission based on interaction.",
        },
      ],
    },
  ],
  documentRequirements: [
    {
      id: "board_affiliation_certificate",
      label: "Board Affiliation / Recognition Certificate",
      description: "Official board affiliation document or state government recognition letter",
      required: true,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
    {
      id: "society_trust_registration",
      label: "Educational Society / Trust Registration",
      description: "Registration certificate of the society or trust running the school",
      required: false,
      acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    },
  ],
};
